// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhewsGJqwZXiBHXJcZgsetXwiTFd0XfCA',
    appId: '1:1089515102106:web:e2c6f0f89f672d48ef2423',
    messagingSenderId: '1089515102106',
    projectId: 'flutter-gymapp-be968',
    authDomain: 'flutter-gymapp-be968.firebaseapp.com',
    storageBucket: 'flutter-gymapp-be968.appspot.com',
    measurementId: 'G-RD704CWZ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHb8dzujV5XCVP2DtA79YZ7teu-x-1rY',
    appId: '1:1089515102106:android:9d6698c53dbb77eeef2423',
    messagingSenderId: '1089515102106',
    projectId: 'flutter-gymapp-be968',
    storageBucket: 'flutter-gymapp-be968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXxh4C4i0aqcmgaEOhCnExYciDSThoP78',
    appId: '1:1089515102106:ios:19aebba6cefacbd2ef2423',
    messagingSenderId: '1089515102106',
    projectId: 'flutter-gymapp-be968',
    storageBucket: 'flutter-gymapp-be968.appspot.com',
    iosClientId: '1089515102106-mmltm48nqetbrigbuh44r0emphqltio8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGymapp',
  );
}
